"""add salary_estimate column to job_analyses

Revision ID: 0441c78cee78
Revises: b919008b46b7
Create Date: 2026-03-17 16:09:41.572965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0441c78cee78'
down_revision: Union[str, Sequence[str], None] = 'b919008b46b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analyses', sa.Column('salary_estimate', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_analyses', 'salary_estimate')
    # ### end Alembic commands ###
