"""create job_analyses table

Revision ID: 1867413aa846
Revises: 
Create Date: 2026-03-17 11:36:01.834495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1867413aa846'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('job_title', sa.String(length=256), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('should_apply', sa.Boolean(), nullable=False),
    sa.Column('one_line_verdict', sa.String(length=512), nullable=False),
    sa.Column('direct_matches', sa.JSON(), nullable=False),
    sa.Column('transferable', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('green_flags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_analyses_url'), 'job_analyses', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_analyses_url'), table_name='job_analyses')
    op.drop_table('job_analyses')
    # ### end Alembic commands ###
