"""add applied column to job_analyses

Revision ID: b919008b46b7
Revises: 1867413aa846
Create Date: 2026-03-17 14:16:13.241050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b919008b46b7'
down_revision: Union[str, Sequence[str], None] = '1867413aa846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('job_analyses', sa.Column(
        'applied',
        sa.Boolean(),
        nullable=False,
        server_default='false'
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_analyses', 'applied')
    # ### end Alembic commands ###
